name: Deploy-Container

on: [workflow_dispatch, push]

jobs:
    deploy:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout
          uses: actions/checkout@v4
    
        - name: Log in to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
    
        - name: Use the Docker buildx tool
          run: |
            docker buildx create --use
    
        - name: Build and deploy Docker image to GHCR
          run: |
            docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/coopeaus/nes-emulator/build-lint-container:latest --push -f docker/alpine-Dockerfile .