name: lint-format

on: [pull_request]

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check for changes in C++ files
        id: check_changes
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\.(cpp|h|hpp|c)$' || echo "No C++ file changes"
        continue-on-error: true

      - name: Skip linting if no C++ files changed
        if: steps.check_changes.outputs.result == 'No C++ file changes'
        run: |
          echo "No C++ file changes, skipping linting."
          exit 0
  
      - name: Create build directory # needed for linting
        run: |
          rm -rf build
          mkdir -p build
          cd build
          cmake ..
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          version: "18"
          style: "file"
          tidy-checks: ""
          no-lgtm: false
          thread-comments: true
          step-summary: true
          tidy-review: true
          format-review: true
          database: "./build/compile_commands.json"

      - name: Report failure
        if: steps.linter.outputs.checks-failed != 0
        run: exit 1
