name: lint-format

on: [push, pull_request]

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check for changes in C++ files
        id: check_changes
        run: |
          git fetch origin main
            CHANGED_FILES=$(git diff --name-only origin/main)
            echo "Changed files: $CHANGED_FILES"
            if echo "$CHANGED_FILES" | grep -E '\.(cpp|h|hpp)$'; then
              echo "C++ files were modified."
              echo "files_modified=true" >> $GITHUB_ENV
            else
              echo "No C++ files were modified."
              echo "files_modified=false" >> $GITHUB_ENV
        continue-on-error: true
          
      - name: Skip linting if no C++ files changed
        if: ! env.files_modified
        run: |
          echo "No C++ file changes, skipping linting."

      - name: Create build directory # needed for linting
        if: env.files_modified
        run: |
          rm -rf build
          mkdir -p build
          cd build
          cmake ..

      - name: Run linter
        if: env.files_modified
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: "18"
          style: "file"
          tidy-checks: ""
          no-lgtm: false
          thread-comments: true
          step-summary: true
          tidy-review: true
          format-review: true
          database: "./build/compile_commands.json"

      - name: Report failure
        if: steps.linter.outputs.checks-failed != 0 && env.files_modified
        run: exit 1

      - name: Report Success
        if: ! env.files_modified
        run: exit 0
